---
title: "About Me"
sidebar: false 
---

# My CV

You can download my cv by clicking [here](https://drive.google.com/uc?export=download&id=1cEcxl46giZzqb-n_hEguQj6ZYRuR2wdY)

# Education

-   B.S., Industrial Engineering, Hacettepe University, Turkey, 2019 - ongoing.
-   Minor, Business Administration, Hacettepe University, Turkey, 2022 - ongoing.
-   Erasmus+ Exchange Program, University of Lodz, Poland, 2021-2022

# Work Experience

## Employments

1.  PFSA Turkey, Content Editor, 20222-Ongoing
2.  Superior Shores Resort, Housekeeping, 2023

## Internships

1.  Turkish Aerospace Industries, Production Planning Engineering Internship, 2022-Ongoing

2.  YapıKredi, Summer Internship Program, 2022

3.  İller Bankası, Financial Management Engineering Internship, 2022

# Projects

1.  Global AI Hub Deep Learning Bootcamp, Classification of city Sounds by using deep learning applications

# Languages

Fluent in Turkish and English, Enthusiastic to learn German and Polish

# Competencies

R, Quarto, Git, Python, Excel, Powerpoint, Solidworks, SQL, Minitab, MRP-ERP, Matlab, Premiere Pro

# Hobbies and Interests

Professional Volleyball Player, Video Games, Amateur Photography
